### ISSUE TITLE
Array index out of range error, global prop replacement broken

### ISSUE THREAD

**Issue by sergjack2015** [klyte45/PropSwitcher#1]
After the recent update, there is occasional prop and vehicle flickering, and Array index out of range error. Also, the "global" prop replacement doesn't seem to actually affect all props.
[output_log.txt](https://github.com/klyte45/PropSwitcher/files/6134729/output_log.txt)
[AutoRepair.log](https://github.com/klyte45/PropSwitcher/files/6134730/AutoRepair.log)

![20210313125629_1](https://user-images.githubusercontent.com/80580018/111029546-7f431780-83fd-11eb-8cd6-d7008e4be4db.jpg)

**Comment by klyte45** [comment]
Are you using placed props? Like the park props or via Find It?

**Comment by klyte45** [comment]
Anyway, I got it. It start happening in r1 patch, the original version didn't had this bug.
Working in a solution.

**Comment by klyte45** [comment]
Fixed in latest commit, version 1.3.0 r2. Already uploaded to Workshop.

**Comment by sergjack2015** [comment]
I'll test now, thanks for fast comment

**Comment by sergjack2015** [comment]
Ok so I've tested the new update, and I still get the same problems...
[output_log.txt](https://github.com/klyte45/PropSwitcher/files/6135580/output_log.txt)

**Comment by klyte45** [comment]
Are you sure was the mod updated by steam? Check the version after loading a city on pause menu. It must be:
![image](https://user-images.githubusercontent.com/11671356/111044553-0b6a3480-8428-11eb-855f-235cba9091aa.png)

**Comment by sergjack2015** [comment]
Alright, imma load my game again and see...

**Comment by sergjack2015** [comment]
ok I have the new version
I'll try loading now

**Comment by sergjack2015** [comment]
I've loaded into the save, and while all prop replacements work properly, I still get Array index out of range error.
[output_log.txt](https://github.com/klyte45/PropSwitcher/files/6135710/output_log.txt)

**Comment by sergjack2015** [comment]
I've heard from some ppl that it might have something to do with NeXT 2, although I have not tested this.

**Comment by klyte45** [comment]
Well, I'm assuming that if you disable Prop Switcher the errors will vanish, right?
I will need to take more time to  find a solution, since I couldn't reproduce it right now. But I bet on a mod incompatibility issue - no idea which one yet.

I'll take a look in the NeXT2. I guess it currently abandoned... I will get back with the results soon.

**Comment by sergjack2015** [comment]
Disabling Prop Switcher, or removing all (or some specific) replacement rules causes the game to freeze, and for buildings/vehicles/some segments to dissapear completely.

**Comment by klyte45** [comment]
Definitely it's a mod conflict. Prop Switcher alone don't have this behaviour.
Checking now

**Comment by klyte45** [comment]
No, it's not NeXT2...

**Comment by klyte45** [comment]
> Disabling Prop Switcher, or removing all (or some specific) replacement rules causes the game to freeze, and for buildings/vehicles/some segments to dissapear completely.

Anyway, can you send your log right after this error happens? Maybe there's a clue

PS: If possible, activate the debug mode option before it, and then reload the game before loading the city

**Comment by sergjack2015** [comment]
Ok this is the log from when I tried to load game without Prop Switcher...
[output_log.txt](https://github.com/klyte45/PropSwitcher/files/6135831/output_log.txt)
...and I couldn't even enter the saved game.

**Comment by klyte45** [comment]
Now there's a lot of exceptions like this: 
```
NullReferenceException: Object reference not set to an instance of an object
at RandomTreeRotation.TreeInstanceDetour.RenderInstance (RenderManager/CameraInfo,TreeInfo,UnityEngine.Vector3,single,single) <0x0075c>
```
Seems that there's a third mod making a mess with Prop Switcher and Randon Tree Rotation mods. I see you use the  **TM:PE 11.5.0 LABS** which is a beta channel mod. I'm very unlikely to believe it can be the cause but it could be.

Anyway, I saw that you disabled Prop Switcher and then loaded the game. The recommended flow is to disable, close the game and then load a savegame. May you should try again.

**Comment by sergjack2015** [comment]
I'll try that tomorrow, and I'll also try with a different savegame (unlikely to change anything but who knows)

**Comment by sergjack2015** [comment]
Alright, I've tried w/your reccomended flow,and still get the same situation (not being able to enter save game). I'll try with a different save now...
[output_log.txt](https://github.com/klyte45/PropSwitcher/files/6136508/output_log.txt)

**Comment by sergjack2015** [comment]
I've tried a diff save w/o Prop Switcher, and everything seems to work...
[output_log.txt](https://github.com/klyte45/PropSwitcher/files/6136604/output_log.txt)

**Comment by sergjack2015** [comment]
Ok so after some testing, it seems that some saves work without Prop Switcher, but some don't and freeze as soon as they are loaded.

**Comment by sergjack2015** [comment]
And when I have Prop Switcher turned on, I get errors, as before.
[output_log.txt](https://github.com/klyte45/PropSwitcher/files/6137238/output_log.txt)
Also, the errors mostly appear when NoBigTruck is doing checking, but I don't think that those are related.

**Comment by klyte45** [comment]
I'm looking the debug data, it seems there's something wrong... I will check it deeper now

**Comment by sergjack2015** [comment]
I've just tested it, NoBigTruck doesn't seem to be the cause of this...

**Comment by sergjack2015** [comment]
This is the error that happens every now and then (cca every 30secs, but at irregular intervals)

`1,939,062ms | Simulation error: Array index is out of range.
at TreeInstance.PopulateGroupData (TreeInfo,UnityEngine.Vector3,single,single,UnityEngine.Vector4,int&,int&,UnityEngine.Vector3,RenderGroup/MeshData,UnityEngine.Vector3&,UnityEngine.Vector3&,single&,single&) <0x006d5>
at (wrapper dynamic-method) BuildingAI.BuildingAI.PopulatePropGroupData_Patch0 (BuildingAI,uint16,Building&,bool,bool,int,int,int,int&,int&,UnityEngine.Vector3,RenderGroup/MeshData,UnityEngine.Vector3&,UnityEngine.Vector3&,single&,single&) <0x0170c>
at BuildingAI.PopulateGroupData (uint16,Building&,single&,int,int,int,int&,int&,UnityEngine.Vector3,RenderGroup/MeshData,UnityEngine.Vector3&,UnityEngine.Vector3&,single&,single&) <0x00392>
at CommonBuildingAI.PopulateGroupData (uint16,Building&,single&,int,int,int,int&,int&,UnityEngine.Vector3,RenderGroup/MeshData,UnityEngine.Vector3&,UnityEngine.Vector3&,single&,single&) <0x04097>
at Building.PopulateGroupData (uint16,int,int,int,int&,int&,UnityEngine.Vector3,RenderGroup/MeshData,UnityEngine.Vector3&,UnityEngine.Vector3&,single&,single&) <0x00112>
at BuildingManager.PopulateGroupData (int,int,int,int&,int&,UnityEngine.Vector3,RenderGroup/MeshData,UnityEngine.Vector3&,UnityEngine.Vector3&,single&,single&,bool&) <0x0013f>
at RenderManager.Managers_PopulateGroupData (int,int,int,int&,int&,UnityEngine.Vector3,RenderGroup/MeshData,UnityEngine.Vector3&,UnityEngine.Vector3&,single&,single&,bool&) <0x000b1>
at RenderGroup.UpdateMeshData (RenderGroup/MeshLayer,UnityEngine.Vector3&,UnityEngine.Vector3&) <0x00391>
at RenderGroup.UpdateMeshData () <0x00155>
at RenderManager.SimulationStepImpl (int) <0x00103>
at SimulationManagerBase`2.SimulationStep (int) <0x0004c>
at RenderManager.ISimulationManager.SimulationStep (int) <0x00024>
at SimulationManager.SimulationStep () <0x00693>
at SimulationManager.SimulationThread () <0x0018a>
  [Core]`

**Comment by sergjack2015** [comment]
This is the last log, where the error can be seen clearly (at the end).
[output_log.txt](https://github.com/klyte45/PropSwitcher/files/6137311/output_log.txt)

**Comment by klyte45** [comment]
Well, I read all logs and everything seems to be ok
My last try is to change some compilation settings that may be incorrect. But before I release, I would ask you to try to use [these mod files](https://github.com/klyte45/PropSwitcher/tree/master/_requiredDLLs) instead of the workshop version. They are at version 1.3.0r3.

The highlighted error stacktrace generally happens when a light effect from a prop isn't accounted and then the game reserve a smaller quantity of vertexes spaces to render the view, and it overflows on BuildingAI when rendering trees because it's the last process. An additional test I could ask you is to check if you have any global rule that uses a prop with effect (like lampposts as example) and then remove all them, the error may disappear. 

Anyway, if you erase all your currently global repacement rules, this error goes away?

**Comment by sergjack2015** [comment]
Ok I'll try the r3 now.

Yes, I am using some light replacement rules, so first I'll try to undo those on the r2 and see what happens.. Then I'll test whether r3 makes those errors go away without needing to replace the lights.

And if I erase all current global rules, my game freezes, and buildings, props, vehicles etc. start flickering or dissapear completely.

**Comment by sergjack2015** [comment]
Removing the light replacement rules on r2 doesn't make the errors go away.

And this is what happens when I try to remove all prop replacements...
![20210314221349_1](https://user-images.githubusercontent.com/80580018/111084511-0504b700-8513-11eb-8a2d-3909eddb98de.jpg)
This is the log from my attempt.
[output_log.txt](https://github.com/klyte45/PropSwitcher/files/6137586/output_log.txt)

**Comment by sergjack2015** [comment]
I'll try r3 now.

**Comment by klyte45** [comment]
Hum, I guess I found something. Have you tried removing Random Tree Rotation mod?
I see its code is very very old, may possibly conflict with the Prop Switcher

**Comment by sergjack2015** [comment]
Yes I've tried that already, and that didn't help.

**Comment by klyte45** [comment]
I also found a lot of _Unknown prefab_ alerts. It means that when the savegame was created, they were available, but they aren't now. This may be harmless, but also be a symptom. Check your Loading Screen Mod report generated after loading the city an search if there are no critical assets missing.

PS: The first names are related to some DLC packs. Which DLCs do you have active now?
```
349,794ms | Unknown prefab: Basic Road Tram  [Serialization]
349,796ms | Unknown prefab: Tram Line  [Serialization]
349,802ms | Unknown prefab: Medium Road Tram  [Serialization]
349,803ms | Unknown prefab: Tram Depot Road  [Serialization]
349,808ms | Unknown prefab: Heating Pipe  [Serialization]
349,814ms | Unknown prefab: Tram Track  [Serialization]
349,819ms | Unknown prefab: Oneway Tram Track  [Serialization]
349,824ms | Unknown prefab: Tram Station Track  [Serialization]
349,825ms | Unknown prefab: Tram Station Track Sunken  [Serialization]
349,835ms | Unknown prefab: Four Lane Highway  [Serialization]
349,841ms | Unknown prefab: Avenue Large With Grass  [Serialization]
349,842ms | Unknown prefab: Avenue Large With Grass Bridge  [Serialization]
349,845ms | Unknown prefab: Ferry Line  [Serialization]
349,846ms | Unknown prefab: Avenue Large With Buslanes Grass  [Serialization]
349,851ms | Unknown prefab: Ferry Path  [Serialization]
349,852ms | Unknown prefab: Two Lane Highway  [Serialization]
349,855ms | Unknown prefab: Two Lane Highway Elevated  [Serialization]
349,858ms | Unknown prefab: Ferry Dock  [Serialization]
349,860ms | Unknown prefab: Asymmetrical Three Lane Road Elevated  [Serialization]
349,861ms | Unknown prefab: Ferry Dockway  [Serialization]
349,869ms | Unknown prefab: Four Lane Highway Connection  [Serialization]
349,871ms | Unknown prefab: Two Lane Highway Connection  [Serialization]
349,877ms | Unknown prefab: 1173882928.6 Lane Road with TramsElevated0  [Serialization]
349,877ms | Unknown prefab: 1173882928.6 Lane Road with Dedicated Tram_Data  [Serialization]
349,877ms | Unknown prefab: 1187866443.Large Avenue With Tram_Data  [Serialization]
349,880ms | Unknown prefab: Oil Industry Fence 01  [Serialization]
349,884ms | Unknown prefab: Industry Road Medium 01 Bridge  [Serialization]
349,885ms | Unknown prefab: Industry Road Medium 01 Elevated  [Serialization]
349,889ms | Unknown prefab: 1224142380.Large Road Elevated0  [Serialization]
349,889ms | Unknown prefab: 1224142380.反向道路3+3 Reverse lane road_Data  [Serialization]
349,889ms | Unknown prefab: 1554363713.Tram Track Elevated0  [Serialization]
349,889ms | Unknown prefab: 1554363713.LRT Tram Tracks_Data  [Serialization]
349,889ms | Unknown prefab: 1559078925.LRT Tram Tracks Single Track_Data  [Serialization]
349,889ms | Unknown prefab: 1564758436.LRT - Middle Station Track#01_Data  [Serialization]
349,890ms | Unknown prefab: 1564760932.LRT - Middle Tr. Extension_Data  [Serialization]
349,890ms | Unknown prefab: 1698282173.DualIslandStationTrack_Elevated_Data  [Serialization]
349,890ms | Unknown prefab: 1707061991.Tram Track Elevated0  [Serialization]
349,890ms | Unknown prefab: 1707061991.Tram Track Slope0  [Serialization]
349,890ms | Unknown prefab: 1707061991.Tram Track Tunnel0  [Serialization]
349,890ms | Unknown prefab: 1707061991.LRT Tram Tracks - Without Fences_Data  [Serialization]
349,890ms | Unknown prefab: 1223954908.32m 4 Stop Tram Exchange_Data  [Serialization]
349,890ms | Unknown prefab: 1717891496.Generic LRT Platforms with Walls_Data  [Serialization]
349,891ms | Unknown prefab: 1717891496.Blank Generic LRT Platforms_Data  [Serialization]
349,891ms | Unknown prefab: 1725915787.Center Tram #01 - Node_Data  [Serialization]
349,897ms | Unknown prefab: 1786570098.LRT Tram Tracks Sngl - fenceless_Data  [Serialization]
349,897ms | Unknown prefab: 1930665850.Asymmetric Medium Tram - Road_Data  [Serialization]
349,897ms | Unknown prefab: 2055979199.Three-Lane One-Way Road w/Trees_Data  [Serialization]
349,897ms | Unknown prefab: 2059289920.One-Lane One-Way Road w/Dbl Prkg_Data  [Serialization]
349,898ms | Unknown prefab: 1224142380.反向道路1+1 Reverse lane road_Data  [Serialization]
349,898ms | Unknown prefab: 1224142380.反向道路2+1 Reserve lane road_Data  [Serialization]
349,898ms | Unknown prefab: 2059292778.One-Lane One-Way Road with Trees_Data  [Serialization]
349,898ms | Unknown prefab: 2066747424.Two-Lane Two-Way Hwy with Median_Data  [Serialization]
349,898ms | Unknown prefab: 2066749066.Two-Lane Two-Way Hwy w/Med + Bar_Data  [Serialization]
349,898ms | Unknown prefab: 2075454805.Three-Lane (1+2) Two-Way Highway_Data  [Serialization]
349,898ms | Unknown prefab: 2075455897.Three-Lane (1+2) Two-Way Hwy w/B_Data  [Serialization]
349,898ms | Unknown prefab: 2089711970.Four-Lane Two-Way Road w/Trees_Data  [Serialization]
349,898ms | Unknown prefab: Hway2lanesmooth.Smooth 2 lane highway_Data  [Serialization]
349,898ms | Unknown prefab: 1608269207.Medium Road Bridge Tram0  [Serialization]
349,899ms | Unknown prefab: 1608269207.4 Lane Road dedicated LRT Tram_Data  [Serialization]
349,899ms | Unknown prefab: 1213488864.Invisible Pedestrian Path 16m_Data  [Serialization]
349,899ms | Unknown prefab: 1213488864.Pedestrian Tunnel3  [Serialization]
349,899ms | Unknown prefab: 1205312481.Asymmetrical Three Lane Road Elevated0  [Serialization]
349,899ms | Unknown prefab: 1366497445.Tram with Central Median_Data  [Serialization]
349,899ms | Unknown prefab: 1251726663.Two-Lane Suburban Street_Data  [Serialization]
349,899ms | Unknown prefab: 1253042356.Two-Lane Suburban Street Alt_Data  [Serialization]
349,899ms | Unknown prefab: 1291386335.6 Lane Road with TramsElevated0  [Serialization]
349,899ms | Unknown prefab: 1291386335.M 4-lane Ded Tram  w Trees_Data  [Serialization]
349,899ms | Unknown prefab: 1291387630.M 4-lane Ded Tram  Stop 2 side_Data  [Serialization]
349,900ms | Unknown prefab: 1291388734.M 4-lane Ded Tram  Stop 1 side_Data  [Serialization]
349,900ms | Unknown prefab: 1778587650.Small 2-lane - Tram Road_Data  [Serialization]
349,900ms | Unknown prefab: 2001117996.LRT Avenue_Data  [Serialization]
349,900ms | Unknown prefab: 2005366935.LRT Avenue - plain_Data  [Serialization]
349,900ms | Unknown prefab: 1205474233.Cobblestone Wavy Alternate_Data  [Serialization]
349,900ms | Unknown prefab: 1353858761.Tram Track with Right Platform_Data  [Serialization]
349,900ms | Unknown prefab: 1353859017.Tram Track with Left Platform_Data  [Serialization]
349,900ms | Unknown prefab: 1354482042.Tram Tracks with Platforms_Data  [Serialization]
349,900ms | Unknown prefab: 1309847529.Two-Lane Brick Suburban Street_Data  [Serialization]
349,900ms | Unknown prefab: 1376780406.Stone quay_Data  [Serialization]
349,901ms | Unknown prefab: 1376817566.Stone quay - Plain_Data  [Serialization]
349,901ms | Unknown prefab: 2120514201.Four-Lane (1+3) Two-Way Road w/T_Data  [Serialization]
349,901ms | Unknown prefab: 1397254833.Stone quay fenced_Data  [Serialization]
349,901ms | Unknown prefab: 2130577793.Four-Lane Two-Way Rd w/Tram Trks_Data  [Serialization]
349,901ms | Unknown prefab: 2143245486.Two-Lane Two-Way Rd w/Tram Track_Data  [Serialization]
349,901ms | Unknown prefab: 2146093450.Two-Lane Two-Way Rd w/Tram Tk NP_Data  [Serialization]
349,901ms | Unknown prefab: 2146099365.Two-Lane One-Way Rd w/Tram Ln NP_Data  [Serialization]
349,901ms | Unknown prefab: 1608289031.Tram Track - Asphalt_Data  [Serialization]
349,901ms | Unknown prefab: 1480978920.Invisible Pedestrian Path (8m)_Data  [Serialization]
349,901ms | Unknown prefab: 2161731780.Three-Lane (1+2) Two-Way Rd w/Tr_Data  [Serialization]
349,902ms | Unknown prefab: 2163847072.Three-Lane (1+2) Two-Way Road NP_Data  [Serialization]
349,902ms | Unknown prefab: 1758684151.Four Lane - Tram Road_Data  [Serialization]
349,902ms | Unknown prefab: 1391209732.Contemporary Shared St P Both_Data  [Serialization]
349,902ms | Unknown prefab: 1404646325.Sound barrier 01_Data  [Serialization]
349,902ms | Unknown prefab: 2005366935.LRT Avenue - nodeless_Data  [Serialization]
349,902ms | Unknown prefab: 2005366935.LRT Avenue - downunder nodeless_Data  [Serialization]
349,902ms | Unknown prefab: 1405253131.Sound Barrier - Wavy Decorated_Data  [Serialization]
349,902ms | Unknown prefab: 1418364828.Chainlink Standard Fence_Data  [Serialization]
349,902ms | Unknown prefab: 1533069018.Contemporary Pedestrian Street_Data  [Serialization]
349,902ms | Unknown prefab: 2055586349.Stone quay decorated_Data  [Serialization]
349,902ms | Unknown prefab: 1480409620.R69 Terraforming Network_Data  [Serialization]
349,903ms | Unknown prefab: 2130576379.Four-Lane Two-Way Rd w/Tm Lns NP_Data  [Serialization]
349,903ms | Unknown prefab: 1632829475.Two-Lane Rd w Tree Mdn, Parking_Data  [Serialization]
349,903ms | Unknown prefab: 1632829475.Two-Lane Rd w Grass Mdn, Parking_Data  [Serialization]
349,903ms | Unknown prefab: 1632829475.Two-Lane Rd w Median, Parking_Data  [Serialization]
349,903ms | Unknown prefab: 1632829475.Two-Lane Road with Tree Median_Data  [Serialization]
349,903ms | Unknown prefab: 1614339011.Train Track Elevated0  [Serialization]
349,903ms | Unknown prefab: 1614339011.Train Track Bridge0  [Serialization]
349,903ms | Unknown prefab: 1614339011.Train Track Slope0  [Serialization]
349,903ms | Unknown prefab: 1806489009.NL 2W Res St Rd/Gy Brick (Base)_Data  [Serialization]
349,903ms | Unknown prefab: 2146090526.Two-Lane Two-Way Rd w/Trm Tks NP_Data  [Serialization]
349,904ms | Unknown prefab: 2146096372.Two-Lane One-Way Rd w/Trm Trk NP_Data  [Serialization]
349,904ms | Unknown prefab: 1806489849.NL 2W Res St Rd/Gy Brick (Tree)_Data  [Serialization]
349,904ms | Unknown prefab: 1614339011.Train Track Tunnel0  [Serialization]
349,904ms | Unknown prefab: 1695486256.Stone Retaining Wall_Data  [Serialization]
349,904ms | Unknown prefab: 1614339011.Swiss track D2_Data  [Serialization]
349,904ms | Unknown prefab: 1701239865.Namba Park Retaining Wall_Data  [Serialization]
349,904ms | Unknown prefab: 2175157194.6L 2 + 3 Asym_Data  [Serialization]
349,904ms | Unknown prefab: 1618536671.Swiss track S2_Data  [Serialization]
349,904ms | Unknown prefab: 2175155543.4L TW Road (2L) Concrete_Data  [Serialization]
349,904ms | Unknown prefab: 2175155813.5L TW Asym Lane (2/3L) Concrete_Data  [Serialization]
349,905ms | Unknown prefab: 2175156175.5L TW Asym Road (2L+3L) Concrete_Data  [Serialization]
349,905ms | Unknown prefab: 2175156479.Medium Road Elevated0  [Serialization]
349,905ms | Unknown prefab: 2175156479.6L TW Road (2L+1P) Concrete_Data  [Serialization]
349,905ms | Unknown prefab: 2175156665.6L TW Road (3L) Concrete_Data  [Serialization]
349,905ms | Unknown prefab: 2175156913.6L TW Road (3L/2L+1P) Concrete_Data  [Serialization]
349,905ms | Unknown prefab: 2175157194.7L Road Lane (4+2+1p) Concrete_Data  [Serialization]
349,905ms | Unknown prefab: 2175157464.7L TW Road (4+3) Concrete_Data  [Serialization]
349,905ms | Unknown prefab: 2175157673.7L TW Road Lane (4+3) Concrete_Data  [Serialization]
349,905ms | Unknown prefab: 2175157880.7L TW Road Parking (4+2+P) Concr_Data  [Serialization]
349,905ms | Unknown prefab: 1752701943.Swanky Street Temperate_Data  [Serialization]
349,906ms | Unknown prefab: 1622570950.Swiss track S1_Data  [Serialization]
349,906ms | Unknown prefab: 1623716821.Swiss track D2 (Sta. NC)_Data  [Serialization]
349,906ms | Unknown prefab: 1875956729.Surface Network Asphalt c 16m_Data  [Serialization]
349,906ms | Unknown prefab: 1651161894.Train Track Elevated0  [Serialization]
349,906ms | Unknown prefab: 1651161894.Non electrified track D2_Data  [Serialization]
349,906ms | Unknown prefab: 1875956729.Surface Network Asphalt b 8m_Data  [Serialization]
349,906ms | Unknown prefab: 1699341209.Light Stone Retaining Wall_Data  [Serialization]
349,906ms | Unknown prefab: 1738014454.Swiss track D2 (E-Sta_NP)_Data  [Serialization]
349,906ms | Unknown prefab: 1830206912.Swiss track D2 (E-Sta_NC_NP)_Data  [Serialization]
349,906ms | Unknown prefab: 1581526585.Pedestrian Elevated0  [Serialization]
349,907ms | Unknown prefab: 1875956729.Surface Network Grass b 8m_Data  [Serialization]
349,907ms | Unknown prefab: 1581526840.Pedestrian Elevated0  [Serialization]
349,907ms | Unknown prefab: 2130577793.Asymmetrical Three Lane Road Elevated0  [Serialization]
349,907ms | Unknown prefab: 2187478449.R0Railway Altona Deco 02_Data  [Serialization]
349,907ms | Unknown prefab: 2320349745.Pedestrian Path #01 - 2/2_Data  [Serialization]
349,907ms | Unknown prefab: 2320350332.Pedestrian Path #02 - 2/2_Data  [Serialization]
349,907ms | Unknown prefab: 2320350768.Pedestrian Path #03 - 2/2_Data  [Serialization]
349,907ms | Unknown prefab: 2135348211.Five-Lane (2+3) Two-Way Rd w/Trs_Data  [Serialization]
349,907ms | Unknown prefab: 2141817096.Four-Lane Two-Way Rd w/Median Tr_Data  [Serialization]
349,907ms | Unknown prefab: 1889652689.Highway Elevated0  [Serialization]
349,908ms | Unknown prefab: 1889652689.2L - National Road_Data  [Serialization]
349,908ms | Unknown prefab: 2163847072.Asymmetrical Three Lane Road Elevated1  [Serialization]
349,908ms | Unknown prefab: 1889653985.Highway Elevated1  [Serialization]
349,908ms | Unknown prefab: 1889653985.4L - National Road_Data  [Serialization]
349,908ms | Unknown prefab: 2111479730.Surface Network Asphalt 16mD_Data  [Serialization]
349,908ms | Unknown prefab: 1889660581.Soundwall with Steel Barrier_Data  [Serialization]
349,908ms | Unknown prefab: 2059287443.One-Lane One-Way Road (No Prkg)_Data  [Serialization]
349,908ms | Unknown prefab: 1889660581.Soundwall _Data  [Serialization]
349,908ms | Unknown prefab: 2111479730.Surface Network Asphalt 8mD_Data  [Serialization]
349,908ms | Unknown prefab: 2111479730.Surface Network Asphalt 4mD_Data  [Serialization]
349,908ms | Unknown prefab: 2264071712.Medium Road Elevated0  [Serialization]
349,909ms | Unknown prefab: 2264072726.Six-Lane Avenue with Trees NP_Data  [Serialization]
349,909ms | Unknown prefab: 2040732427.nn4 Concrete Pedestrian Path 4m Elevated  [Serialization]
349,909ms | Unknown prefab: 2105375780.R69 Station Shelter 2 W_Data  [Serialization]
349,909ms | Unknown prefab: 2040732427.nn4 Concrete Pedestrian Path 4m Tunnel  [Serialization]
349,909ms | Unknown prefab: 2040732427.nn4 Concrete Pedestrian Path 8m Elevated  [Serialization]
349,909ms | Unknown prefab: 2040732427.nn4 Concrete Pedestrian Path 8m Slope  [Serialization]
349,909ms | Unknown prefab: 2254730225.Retaining Wall - Narrow#01_Data  [Serialization]
349,909ms | Unknown prefab: 2310196401.MSP Platform Network German-N_Data  [Serialization]
349,909ms | Unknown prefab: 2320349745.Pedestrian Elevated0  [Serialization]
349,909ms | Unknown prefab: 2040732427.nn4 Concrete Pedestrian Path 8m Tunnel  [Serialization]
349,910ms | Unknown prefab: 2040732427.nn4 Concrete Pedestrian Path 8m_Data  [Serialization]
349,910ms | Unknown prefab: 2320350768.Pedestrian Elevated0  [Serialization]
349,910ms | Unknown prefab: 2324581772.Historic Main Street_Data  [Serialization]
349,910ms | Unknown prefab: 2254730225.Retaining Wall - Wall#01 (half)_Data  [Serialization]
349,910ms | Unknown prefab: 2254730225.Rtnng Wll - Soundwall#01_Data  [Serialization]
349,910ms | Unknown prefab: 2254730225.Retaining Wall - Wall#01_Data  [Serialization]
349,910ms | Unknown prefab: 2254730225.Retaining Wall - Plain#01_Data  [Serialization]
349,910ms | Unknown prefab: 2320350332.Pedestrian Elevated0  [Serialization]
349,910ms | Unknown prefab: 2320350768.Pedestrian Slope0  [Serialization]
349,911ms | Unknown prefab: 2320350768.Pedestrian Tunnel0  [Serialization]
349,911ms | Unknown prefab: 2320350332.Pedestrian Elevated1  [Serialization]
349,911ms | Unknown prefab: 2320350332.Pedestrian Slope0  [Serialization]
349,911ms | Unknown prefab: 2320350332.Pedestrian Tunnel0  [Serialization]
349,911ms | Unknown prefab: 2320350768.Pedestrian Elevated1  [Serialization]
349,911ms | Unknown prefab: 2310196401.MSP Platform Network German-O_Data  [Serialization]
349,911ms | Unknown prefab: 2394737923.Brick Retaining Wall_Data  [Serialization]
349,911ms | Unknown prefab: 1186115011.Green pedistrian street_Data  [Serialization]
```

**Comment by sergjack2015** [comment]
Hmm, this is really weird, bc I literally remember seeing some nets in game listed here as "unknown prefabs" (like some rails and quays), so I'd say they are definetly not missing.

**Comment by klyte45** [comment]
Another possible source of problem: MOM. Look this exception while loading meta tags for stations tracks replacements:
```
NullReferenceException: Object reference not set to an instance of an object
  at MetroOverhaul.SetStationCustomizations.ModifyStation (.BuildingInfo info, MetroOverhaul.StationTrackCustomizations pathCustomization, MetroOverhaul.ParentStationMetaData parentMetaData) [0x00000] in <filename unknown>:0 
  at MetroOverhaul.AssetsUpdater.UpdateBuildingsMetroPaths (LoadMode mode, Boolean toVanilla) [0x00000] in <filename unknown>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
MetroOverhaul.AssetsUpdater:UpdateBuildingsMetroPaths(LoadMode, Boolean)
MetroOverhaul.LoadingExtension:OnLevelLoaded(LoadMode)
LoadingWrapper:LoadingWrapper.OnLevelLoaded_Patch6(LoadingWrapper, UpdateMode)
<LoadLevelComplete>c__Iterator9:LoadingManager+<LoadLevelComplete>c__Iterator9.MoveNext_Patch1(<LoadLevelComplete>c__Iterator9)
LoadingManager:FpsBoosterUpdate()
BehaviourUpdater.Updater:Update()
 ```
 I would suggest you to try load once after configuring MOM to use the ghost mode

**Comment by sergjack2015** [comment]
Also something interesting I've noted: I use custom arrows in my city (replaced with Prop Switcher), and this is how they look like after I loaded my save, but before saving.
![20210314230916_1](https://user-images.githubusercontent.com/80580018/111086124-df7bab80-851a-11eb-9e3b-2b059f7912ce.jpg)

After I save, TMPE arrow configs get loaded and some arrows change as a result. And for some reason those arrows lose their replacement rule and convert back to vanilla arrows.
![20210314230952_1](https://user-images.githubusercontent.com/80580018/111086166-0639e200-851b-11eb-9e80-3bff418cbe25.jpg)

And even with r3, the errors still persist...
[output_log.txt](https://github.com/klyte45/PropSwitcher/files/6137684/output_log.txt)

**Comment by klyte45** [comment]
Analyzing your savegame's Prop Switcher XML, I noted that there are some of entries for individual assets:
![image](https://user-images.githubusercontent.com/11671356/111086153-75064380-84f9-11eb-9a21-fd2a8c83ca5e.png)
It may affect that test you did removing the lights rules: they should be removed from here too.

About the arrows, try removing their rules. The errors get gone? I wasn't expecting TMPE to replace it.
Or easier, disable TMPE and enter in the game.

**Comment by sergjack2015** [comment]
I tried with the individual light replacements, and removing arrow replacements... and I still get errors.

I'll try to load the game w/o TMPE, but tomorrow cuz it's getting late now.

**Comment by klyte45** [comment]
no problem. I'm researching the TMPE here also, and I post here if I have any news

**Comment by klyte45** [comment]
[Issue for TMPE team](https://github.com/CitiesSkylinesMods/TMPE/issues/1064)

Seems that TMPE have some kind of fault, may be related to your problem, once the road arrow changes aren't caring about the Prop Switcher rules. I bet that you game will work fine if you remove TMPE, the first exception can be caused on an appliance of rules from TMPE, specially if you have rules removing some arrows like your savegame rules are telling to me.

Once you remove the arrows from rendering calculation but TMPE still rendering them, it will cause the render buffer to be overflowed due there having more assets to render than expected on initial calculations. 

I haven't got it because I don't use TMPE...

**Comment by sergjack2015** [comment]
I've tried disabling TMPE, and now it's even worse... While the Array errors might be gone ), the savegame freezes almost immediately upon load, and thus I couldn't test whether there are any actual errors. But here's the log, maybe you find something.
[output_log.txt](https://github.com/klyte45/PropSwitcher/files/6140685/output_log.txt)

**Comment by klyte45** [comment]
Well, I suggest to see the Loading screen mod files. Seems that are some errors loading NetInfos, if it's true the game can not be able to load the savegame properly.
Also it can be caused by the action of loading a savegame that use TMPE but without the mod itself, but don't know. At least now is clear that the problem with Prop Switcher is that listed above with TMPE...

If you want, you can send the LSM report here too

**Comment by sergjack2015** [comment]
Which one do you need? The most recent one or some other? Also, I'm not quite sure how can I send that, since I can't upload HTML documents here...

**Comment by sergjack2015** [comment]
Also, the report itself lists only 3 assets as missing, and those 3 are all some unimportant stuff I was working on, so nothing critical.

**Comment by sergjack2015** [comment]
Also also, is there a place where I can get the old version of Prop Switcher, so that I can at least play CS while the guys from TMPE fix their mod.

**Comment by klyte45** [comment]
You can get the 1.3 original version here: https://github.com/klyte45/PropSwitcher/tree/41ef679c0c83cd01893b1b32485d28197bb3b294/_requiredDLLs

I didn't created yet tags for older versions, but you can browse the commits to find them. The message commit of each version starts with `v1.X.Y rZ`

**Comment by sergjack2015** [comment]
So if I want 1.2 (the last stable version for me) I'll have to browse commits and find it from there?

**Comment by klyte45** [comment]
V1.2 from November is here: https://github.com/klyte45/PropSwitcher/tree/a396bbe68e29d252b65d0c3a6bed0ebe5f643101/_requiredDLLs

I did a fix some days ago, not sure if it will be fit for you.

**Comment by sergjack2015** [comment]
I'll try that now (I actually downloaded r1 that was updated some days ago but let's see if that works).

**Comment by klyte45** [comment]
Well, feel free to try any version. 

Be sure you are using a release version (with the commit message I exemplified above), I advice. I guess 1.3 won't work against the current TMPE bug because the version caches the result, and the cache of the game isn't being released by them when it's changed by that mod.

**Comment by sergjack2015** [comment]
Ok so 1.2.r1 doesn't seem to work at all... I'll try r0 now.

**Comment by klyte45** [comment]
Well, feel free to try any version. 

Be sure you are using a release version (with the commit message I exemplified above), I advice. I guess 1.3 won't work against the current TMPE bug because the version caches the result, and the cache of the game isn't being released by them when it's changed by that mod.

**Comment by sergjack2015** [comment]
Ok so I've loaded r0, and for some reason the replacement rules get deleted, and I can't import them from the local library.
As a result, the game behaves the same way as when I try to remove those prop replacements.
[output_log.txt](https://github.com/klyte45/PropSwitcher/files/6143932/output_log.txt)

**Comment by klyte45** [comment]
Well, I have bad news for you. The mod was not designed for rollbacks, and I did some XML breaking changes, that works well in 1.2=>1.3, but definitely won't work in inverse way. It will work anyway if you load an save saved with the version 1.2, but I suggest you to backup your library XMLs

**Comment by klyte45** [comment]
Anyway, in theory, you can use the 1.3 if you remove all rules related to turning arrows, specially the ones that removes it.

**Comment by sergjack2015** [comment]
I'll try that tomorrow, as well as as 1.2.r0, and seeing what happens.

**Comment by sergjack2015** [comment]
Ok so r0 seems to be working properly, with no errors. I guess I'll be using it until TMPE gets updated.

**Comment by klyte45** [comment]
If I see they will spent so much time to fix it, I will try to do a patch on their mod.

**Comment by klyte45** [comment]
Just for tracking, this is the current dependency for this fix:
- [ ]  CitiesSkylinesMods/TMPE#1064

**Comment by sergjack2015** [comment]
Oh and another question. Where does this mod save it's replacement rules? Is it in savegame, or in a separate file?

**Comment by klyte45** [comment]
It's saved in savegame, but can be exported/imported if you need to backup or want to change something manually. The export button is available in top each tab.
![image](https://user-images.githubusercontent.com/11671356/115975473-615bed00-a53b-11eb-8520-5c6eee3cee32.png)

**Comment by sergjack2015** [comment]
Is there a way that you can delete those rules from the savegame without having to use Prop Switcher? bc the mod has started crashing my game and there is no way to reliably start my game w/ it anymore, and it's replacements are also making some props sink below ground.

**Comment by klyte45** [comment]
Just disable the mod and its data will not be loaded when loading the game.

**Comment by sergjack2015** [comment]
Oh and also

**Comment by sergjack2015** [comment]
![image](https://user-images.githubusercontent.com/80580018/115987529-afadd200-a5b5-11eb-9525-6731111ae4bb.png)

**Comment by sergjack2015** [comment]
this might be related to prop switcher

**Comment by sergjack2015** [comment]
these are vanilla hedges that have sunk below ground after I used PS to replace them some time ago

**Comment by sergjack2015** [comment]
[output_log.txt](https://github.com/klyte45/PropSwitcher/files/6371615/output_log.txt)
this is the log from the session in which I took that screenshot (and that was without PS)

**Comment by klyte45** [comment]
Well, there's a lot of errors in this exception log, but Prop Switcher isn't even mentioned in any of them. The mod name literally doesn't exists in this log.
Nothing to do from my side, then...
